QuickBlog/Models/HomeViewModels/AuthorViewModel.cs
using PagedList.Core;
using QuickBlog.Data.Models;

namespace QuickBlog.Models.HomeViewModels
{
    public class AuthorViewModel
    {
        public ApplicationUser Author { get; set; }
        public IPagedList<Blog> Blogs { get; set; }
        public string SearchString { get; set; }
        public int PageNumber { get; set; }
    }
}

QuickBlog/Controllers/BlogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuickBlog.BusinessManagers.Interfaces;
using QuickBlog.Models.BlogViewModels;

namespace QuickBlog.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private readonly IBlogBusinessManager _blogBusinessManager;

        public BlogController(IBlogBusinessManager blogBusinessManager)
        {
            _blogBusinessManager = blogBusinessManager;
        }

        [Route("Blog/{id}"), AllowAnonymous]
        public async Task<IActionResult> Index(int? id)
        {
            var actionResult = await _blogBusinessManager.GetBlogViewModel(id, User);

            if (actionResult.Result is null)
                return View(actionResult.Value);

            return actionResult.Result;
        }

        public IActionResult Create()
        {
            return View(new CreateViewModel());
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var actionResult = await _blogBusinessManager.GetEditViewModel(id, User);

            if (actionResult.Result is null)
                return View(actionResult.Value);

            return actionResult.Result;
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateViewModel createBlogViewModel)
        {
            await _blogBusinessManager.CreateBlog(createBlogViewModel, User);

            return RedirectToAction("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Update(EditViewModel editBlogViewModel)
        {
            var actionResult = await _blogBusinessManager.UpdateBlog(editBlogViewModel, User);

            if (actionResult.Result is null)
            {
                return RedirectToAction("Edit", new { editBlogViewModel.Blog.Id });
            }

            return actionResult.Result;
        }
    }
}

QuickBlog/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using QuickBlog.BusinessManagers.Interfaces;
using QuickBlog.Models;
using System.Diagnostics;

namespace QuickBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBlogBusinessManager _blogBusinessManager;
        private readonly IHomeBusinessManager _homeBusinessManager;

        public HomeController(IBlogBusinessManager blogBusinessManager, IHomeBusinessManager homeBusinessManager)
        {
            _blogBusinessManager = blogBusinessManager;
            _homeBusinessManager = homeBusinessManager;
        }

        [Route("/")]
        public IActionResult Index(string searchString, int? page)
        {
            return View(_blogBusinessManager.GetIndexViewModel(searchString, page));
        }

        public IActionResult Author(string authorId, string searchString, int? page)
        {
            var actionResult = _homeBusinessManager.GetAuthorViewModel(authorId, searchString, page);
            if (actionResult.Result is null)
                return View(actionResult.Value);

            return actionResult.Result;
        }
    }
}

QuickBlog/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace QuickBlog.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() =>
            {
                return View();
            });
        }
    }
}

QuickBlog/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace QuickBlog.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() =>
            {
                return View();
            });
        }
    }
}

QuickBlog/ViewComponents/NavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace QuickBlog.ViewComponents
{
    public class NavigationViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() =>
            {
                return View();
            });
        }
    }
}

QuickBlog/Views/Home/Author.cshtml
@model QuickBlog.Models.HomeViewModels.AuthorViewModel
@using PagedList.Core.Mvc
@{
    Layout = "_HomeLayout";
    ViewData["HeaderImage"] = $"../../UserFiles/Users/{Model.Author.Id}/HeaderImage.jpg";
    ViewData["HeaderTitle"] = $"{Model.Author.FirstName} {Model.Author.LastName}";
    ViewData["SubHeader"] = Model.Author.SubHeader;
}

<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                @Html.Raw(Model.Author.AboutContent)
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <form asp-controller="Home" asp-action="Author" class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                    <div class="input-group mb-3">
                        <input name="AuthorId" hidden readonly value="@Model.Author.Id" />
                        <input asp-for="SearchString" type="text" class="form-control" placeholder="Search posts for..." />
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" style="padding: 0 10px 0 10px">Search</button>
                        </div>
                    </div>
                </form>
                <div class="row align-content-center">
                    @foreach (var blog in Model.Blogs) {
                        <div class="col-lg-4 col-md-3 mb-4">
                            <div class="card border-0 shadow">
                                <img src="~/UserFiles/Blogs/@blog.Id/HeaderImage.jpg" class="card-img-top">
                                <div class="card-body">
                                    <div class="row text-center" style="margin: 0px auto 10px 0px;">
                                        <h5 class="card-title text-center w-100"><a asp-controller="Blog" asp-action="Index" asp-route-id="@blog.Id">@blog.Title</a></h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <div list="@Model.Blogs" count="3">
                    <pager class="pager-container" list="@Model.Blogs" options="@PagedListRenderOptions.Bootstrap4PageNumbersPlusPrevAndNext" asp-action="Index" asp-controller="Home" asp-route-query="@Model.SearchString" />
                </div>
            </div>
        </div>
    </div>
</article>

QuickBlog/Views/Home/Index.cshtml
@model QuickBlog.Models.HomeViewModels.IndexViewModel
@using PagedList.Core.Mvc

<div class="container">
    <form asp-controller="Home" asp-action="Index" class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group mb-3">
            <input asp-for="SearchString" type="text" class="form-control" placeholder="Search posts for..." />
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" style="padding: 0 10px 0 10px">Search</button>
            </div>
        </div>
    </form>
    <div class="row align-content-center">
        @foreach (var blog in Model.Blogs) {
            <div class="col-lg-4 col-md-3 mb-4">
                <div class="card border-0 shadow">
                    <img src="~/UserFiles/Blogs/@blog.Id/HeaderImage.jpg" class="card-img-top">
                    <div class="card-body">
                        <div class="row text-center" style="margin: 0px auto 10px 0px;">
                            <h5 class="card-title text-center w-100"><a asp-controller="Blog" asp-action="Index" asp-route-id="@blog.Id">@blog.Title</a></h5>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    <div list="@Model.Blogs" count="20">
        <pager class="pager-container" list="@Model.Blogs" options="@PagedListRenderOptions.Bootstrap4PageNumbersPlusPrevAndNext" asp-action="Index" asp-controller="Home" asp-route-query="@Model.SearchString" />
    </div>
</div>

QuickBlog/Views/Home/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Clean Blog - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    @await Component.InvokeAsync("Navigation")
    <!-- Page Header-->
    @await Component.InvokeAsync("Header")
    <!-- Main Content-->
    <div class="content">
        @RenderBody()
    </div>
    <!-- Footer-->
    @await Component.InvokeAsync("Footer")
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>