QuickBlog/Models/AdminViewModels/AboutViewModel.cs
using QuickBlog.Data.Models;
using System.ComponentModel.DataAnnotations;

namespace QuickBlog.Models.AdminViewModels
{
    public class AboutViewModel
    {
        public ApplicationUser ApplicationUser { get; set; }

        [Display(Name = "Header Image")]
        public IFormFile HeaderImage { get; set; }

        [Display(Name = "Sub-header")]
        public string SubHeader { get; set; }
        public string Content { get; set; }
    }
}

QuickBlog/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuickBlog.BusinessManagers.Interfaces;
using QuickBlog.Models.AdminViewModels;

namespace QuickBlog.Controllers
{
    //[Authorize]
    public class AdminController : Controller
    {
        private readonly IAdminBusinessManager _adminBusinessManager;

        public AdminController(IAdminBusinessManager adminBusinessManager)
        {
            _adminBusinessManager = adminBusinessManager;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _adminBusinessManager.GetAdminDashboard(User));
        }

        public async Task<IActionResult> About()
        {
            return View(await _adminBusinessManager.GetAboutViewModel(User));
        }

        [HttpPost]
        public async Task<IActionResult> UpdateAbout(AboutViewModel aboutViewModel)
        {
            await _adminBusinessManager.UpdateAbout(aboutViewModel, User);
            return RedirectToAction("About");
        }
    }
}

QuickBlog/Controllers/BlogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuickBlog.BusinessManagers.Interfaces;
using QuickBlog.Models.BlogViewModels;

namespace QuickBlog.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private readonly IBlogBusinessManager _blogBusinessManager;

        public BlogController(IBlogBusinessManager blogBusinessManager)
        {
            _blogBusinessManager = blogBusinessManager;
        }

        [Route("Blog/{id}"), AllowAnonymous]
        public async Task<IActionResult> Index(int? id)
        {
            var actionResult = await _blogBusinessManager.GetBlogViewModel(id, User);

            if (actionResult.Result is null)
                return View(actionResult.Value);

            return actionResult.Result;
        }

        public IActionResult Create()
        {
            return View(new CreateViewModel());
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var actionResult = await _blogBusinessManager.GetEditViewModel(id, User);

            if (actionResult.Result is null)
                return View(actionResult.Value);

            return actionResult.Result;
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateViewModel createBlogViewModel)
        {
            await _blogBusinessManager.CreateBlog(createBlogViewModel, User);

            return RedirectToAction("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Update(EditViewModel editBlogViewModel)
        {
            var actionResult = await _blogBusinessManager.UpdateBlog(editBlogViewModel, User);

            if (actionResult.Result is null)
            {
                return RedirectToAction("Edit", new { editBlogViewModel.Blog.Id });
            }

            return actionResult.Result;
        }
    }
}

QuickBlog/ViewComponents/AdminFooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace QuickBlog.ViewComponents
{
    public class AdminFooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() =>
            {
                return View();
            });
        }
    }
}

QuickBlog/ViewComponents/AdminTopNavViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace QuickBlog.ViewComponents
{
    public class AdminTopNavViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() =>
            {
                return View();
            });
        }
    }
}

QuickBlog/Views/Admin/About.cshtml
@model QuickBlog.Models.AdminViewModels.AboutViewModel

<div class="container-fluid">
    <h1 class="mt-4">About Me</h1>
    <div class="row">
        <div class="col-lg-6">
            <div class="card mb-4">
                <form asp-controller="Admin" asp-action="UpdateAbout" method="post" enctype="multipart/form-data">
                    <div class="card-header">
                        <i class="fas fa-pen-fancy mr-1"></i>
                        Update your About Me info!
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="HeaderImage"></label>
                            <div class="custom-file">
                                <input asp-for="HeaderImage" class="custom-file-input" accept="image/*" />
                                <label class="custom-file-label">Choose file</label>
                            </div>
                            <span asp-validation-for="HeaderImage" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SubHeader"></label>
                            <input asp-for="SubHeader" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Content"></label>
                            <textarea asp-for="Content" class="form-control textarea" rows="8"></textarea>
                            <span asp-validation-for="Content" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Submit</button>
                            <a asp-controller="Home" asp-action="Author" asp-route-authorId="@Model.ApplicationUser.Id" class="btn btn-secondary float-right">View</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('.textarea'))
            .catch(error => {
                console.error(error);
            });
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}

QuickBlog/Views/Admin/Index.cshtml
@model QuickBlog.Models.AdminViewModels.IndexViewModel

<div class="container-fluid">
    <h1 class="mt-4">Dashboard</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Dashboard</li>
    </ol>
    <div class="row">
        @foreach (var blog in Model.Blogs) {
            <div class="col-xl-4 col-md-6 mb-4">
                <div class="card border-0 shadow">
                    <img src="~/UserFiles/Blogs/@blog.Id/HeaderImage.jpg" class="card-img-top">
                    <div class="card-body">
                        <div class="row" style="margin: 0px auto 10px 0px;">
                            <div><h5 class="card-title mb-0">@blog.Title</h5></div>
                            <div class="ms-auto me-3 text-end">
                                <i class="fas @(blog.Published ? "fa-eye" : "fa-eye-slash")" style="color: @(blog.Published ? "deepskyblue" : "orangered")"></i>
                            </div>
                        </div>
                        <div class="row ms-0">
                            <div><i class="fas fa-calendar-alt" style="color: gray"></i></div>
                            <p class="text-muted ms-3 mb-0">Last updated on: @blog.UpdatedOn.ToString()</p>
                        </div>
                        <div class="row ms-0" style="bottom: 0;">
                            <div><i class="fas fa-comment" style="color: gray"></i></div>
                            <p class="text-muted ms-3 mb-0">@blog.Comments.Count() comments</p>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col">
                                <a asp-controller="Blog" asp-action="Index" asp-route-id="@blog.Id" class="btn btn-primary">
                                    <i class="fa fa-arrow-circle-right"></i> View
                                </a>
                            </div>
                            <div class="col text-end">
                                <a asp-controller="Blog" asp-action="Edit" asp-route-id="@blog.Id" class="btn btn-secondary float-right">
                                    <i class=" fa fa-edit"></i> Edit
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

QuickBlog/Views/Admin/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - SB Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href="~/css/style.css" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        @await Component.InvokeAsync("AdminTopNav")
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                @await Component.InvokeAsync("AdminSideNav")
            </div>
            <div id="layoutSidenav_content">
                <main>
                    @RenderBody()
                </main>
                @await Component.InvokeAsync("AdminFooter")
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="~/js/script.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="~/assets/demo/chart-area-demo.js"></script>
        <script src="~/assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="~/js/datatables-simple-demo.js"></script>
         @RenderSection("Scripts", required: false)
    </body>
</html>