QuickBlog/Models/BlogViewModels/BlogViewModel.cs
using QuickBlog.Data.Models;

namespace QuickBlog.Models.BlogViewModels
{
    public class BlogViewModel
    {
        public Blog Blog { get; set; }
    }
}

QuickBlog/Models/BlogViewModels/CreateViewModel.cs
using QuickBlog.Data.Models;
using System.ComponentModel.DataAnnotations;

namespace QuickBlog.Models.BlogViewModels
{
    public class CreateViewModel
    {
        [Required, Display(Name = "Header Image")]
        public IFormFile BlogHeaderImage { get; set; }

        public Blog Blog { get; set; }
    }
}

QuickBlog/Models/BlogViewModels/EditViewModel.cs
using QuickBlog.Data.Models;
using System.ComponentModel.DataAnnotations;

namespace QuickBlog.Models.BlogViewModels
{
    public class EditViewModel
    {
        [Display(Name = "Header Image")]
        public IFormFile BlogHeaderImage { get; set; }
        public Blog Blog { get; set; }
    }
}

QuickBlog/Controllers/BlogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuickBlog.BusinessManagers.Interfaces;
using QuickBlog.Models.BlogViewModels;

namespace QuickBlog.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private readonly IBlogBusinessManager _blogBusinessManager;

        public BlogController(IBlogBusinessManager blogBusinessManager)
        {
            _blogBusinessManager = blogBusinessManager;
        }

        [Route("Blog/{id}"), AllowAnonymous]
        public async Task<IActionResult> Index(int? id)
        {
            var actionResult = await _blogBusinessManager.GetBlogViewModel(id, User);

            if (actionResult.Result is null)
                return View(actionResult.Value);

            return actionResult.Result;
        }

        public IActionResult Create()
        {
            return View(new CreateViewModel());
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var actionResult = await _blogBusinessManager.GetEditViewModel(id, User);

            if (actionResult.Result is null)
                return View(actionResult.Value);

            return actionResult.Result;
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateViewModel createBlogViewModel)
        {
            await _blogBusinessManager.CreateBlog(createBlogViewModel, User);

            return RedirectToAction("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Update(EditViewModel editBlogViewModel)
        {
            var actionResult = await _blogBusinessManager.UpdateBlog(editBlogViewModel, User);

            if (actionResult.Result is null)
            {
                return RedirectToAction("Edit", new { editBlogViewModel.Blog.Id });
            }

            return actionResult.Result;
        }
    }
}

QuickBlog/ViewComponents/AdminFooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace QuickBlog.ViewComponents
{
    public class AdminFooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() =>
            {
                return View();
            });
        }
    }
}

QuickBlog/ViewComponents/AdminTopNavViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace QuickBlog.ViewComponents
{
    public class AdminTopNavViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() =>
            {
                return View();
            });
        }
    }
}

QuickBlog/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace QuickBlog.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() =>
            {
                return View();
            });
        }
    }
}

QuickBlog/ViewComponents/NavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace QuickBlog.ViewComponents
{
    public class NavigationViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() =>
            {
                return View();
            });
        }
    }
}

QuickBlog/Views/Blog/Create.cshtml
@model QuickBlog.Models.BlogViewModels.CreateViewModel

<div class="container-fluid">
    <h1 class="mt-4">Create</h1>
    <div class="row">
        <div class="col-lg-6">
            <div class="card mb-4">
                <form asp-controller="Blog" asp-action="Add" method="post" enctype="multipart/form-data">
                    <div class="card-header">
                        <i class="fas fa-pen-fancy mr-1"></i>
                        Write a Blog
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="BlogHeaderImage"></label>
                            <div class="custom-file">
                                <input asp-for="BlogHeaderImage" class="custom-file-input" accept="image/*" />
                                <label class="custom-file-lable">Choose File</label>
                            </div>
                            <span asp-validation-for="BlogHeaderImage" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Blog.Title"></label>
                            <input asp-for="Blog.Title" class="form-control" required />
                            <span asp-validation-for="Blog.Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Blog.Content"></label>
                            <textarea asp-for="Blog.Content" class="form-control textarea" rows="8"></textarea>
                            <span asp-validation-for="Blog.Content" class="text-danger"></span>
                        </div>

                    </div>
                    <div class="card-footer">
                        <div class="form-group">
                            <p class="text-muted">Publish now or save for later edits.</p>
                            <label>Publish now?</label>
                            <input type="checkbox" data-toggle="toggle" asp-for="Blog.Published">
                            <br />
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                        @*                    <p style="color: orangered; margin-bottom: 0;">Please Note:</p>
                        <p>Your post will need to be approved before it is published to the main page. Please feel free to email me to approve your post.</p>
                        *@
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('.textarea'))
            .catch(error => {
                console.error(error);
            });
        $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}

QuickBlog/Views/Blog/Edit.cshtml
@model QuickBlog.Models.BlogViewModels.EditViewModel

<div class="container-fluid">
    <h1 class="mt-4">Edit</h1>
    <div class="row">
        <div class="col-lg-6">
            <div class="card mb-4">
                <form asp-controller="Blog" asp-action="Update" method="post" enctype="multipart/form-data">
                    <input asp-for="Blog.Id" readonly hidden />
                    <div class="card-header">
                        <i class="fas fa-pen-fancy me-1"></i>
                        Edit this Blog
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="BlogHeaderImage"></label>
                            <div class="custom-file">
                                <input asp-for="BlogHeaderImage" class="custom-file-input" accept="image/*" />
                                <label class="custom-file-lable">Choose File</label>
                            </div>
                            <span asp-validation-for="BlogHeaderImage" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Blog.Title"></label>
                            <input asp-for="Blog.Title" class="form-control" required />
                            <span asp-validation-for="Blog.Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Blog.Content"></label>
                            <textarea asp-for="Blog.Content" class="form-control textarea" rows="8"></textarea>
                            <span asp-validation-for="Blog.Content" class="text-danger"></span>
                        </div>

                    </div>
                    <div class="card-footer">
                        <div class="form-group">
                            <p class="text-muted">Publish now or save for later edits.</p>
                            <label>Publish now?</label>
                            <input type="checkbox" data-toggle="toggle" asp-for="Blog.Published">
                            <br />
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                        <p style="color: orangered; margin-bottom: 0;">Please Note:</p>
                        <p>Your post will need to be approved before it is published to the main page. Please feel free to email me to approve your post.</p>

                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('.textarea'))
            .catch(error => {
                console.error(error);
            });
        $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}

QuickBlog/Views/Blog/Index.cshtml
@model QuickBlog.Models.BlogViewModels.BlogViewModel
@{
    Layout = "_HomeLayout";
    ViewData["HeaderImage"] = $"../../UserFiles/Blogs/{Model.Blog.Id}/HeaderImage.jpg";
    ViewData["HeaderTitle"] = Model.Blog.Title;
    ViewData["AuthorName"] = $"{Model.Blog.Creator.FirstName} {Model.Blog.Creator.LastName}";
    ViewData["BlogDate"] = Model.Blog.UpdatedOn.ToString("MMMM d, yyyy");
    ViewData["AuthorId"] = Model.Blog.Creator.Id;
}
@using System.Web
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto testing">
                @Html.Raw(Model.Blog.Content)
@*                @Html.Raw(HttpUtility.HtmlDecode(Model.Blog.Content))
*@            </div>
        </div>
        @*            <div class="row mt-5">
        <div class="col-lg-8 col-md-10 mx-auto">
        <h3 class="mb-5">@Model.Blog.Comments.Count() Comments</h3>
        <ul class="comment-list  comment-top" list="@Model.Blog.Comments" count="0">
        @foreach (var comment in Model.Blog.Comments.Where(comment => comment.Parent is null))
        {
        <li class="comment" style="margin-top: 30px;">
        <div class="comment-body">
        <h4 class="commenter-name">@comment.Author.FirstName @comment.Author.LastName</h4>
        <div class="comment-date">@comment.CreatedOn.ToString("MMMM d, yyyy hh:mm tt")</div>
        <p class="comment-message">@comment.Content</p>
        @if (!User.Identity.IsAuthenticated)
        {
        <a class="reply-btn btn" asp-area="Identity" asp-page="/Account/Login" asp-route-ReturnUrl="~/Blog/@Model.Blog.Id">Login to reply</a>
        }
        else
        {
        <a aria-expanded="false" href="@($"#replyComment{comment.Id}")" data-toggle="collapse" class="reply-btn btn">Reply</a>
        }
        </div>
        @if (User.Identity.IsAuthenticated)
        {
        <div class="collapse" id="@($"replyComment{comment.Id}")">
        <form asp-controller="Blog" asp-action="Comment">
        <input asp-for="Blog.Id" readonly hidden />
        <input asp-for="Comment.Parent.Id" value="@comment.Id" readonly hidden />
        <div class="form-group">
        <label for="comment">Write a reply</label>
        <textarea asp-for="Comment.Content" class="form-control" rows="3"></textarea>
        <button type="submit" class="btn btn-outline-primary Blog-btn">Blog</button>
        </div>
        </form>
        </div>
        }
        <ul class="comment-list" list="@comment.Comments" count="0" style="margin-left: 30px; margin-top:0;">
        @foreach (var reply in comment.Comments)
        {
        <li class="comment">
        <div class="comment-body">
        <h3 class="commenter-name">@reply.Author.FirstName @reply.Author.LastName</h3>
        <div class="comment-date">@reply.CreatedOn.ToString("MMMM d, yyyy hh:mm tt")</div>
        <p class="comment-message">@reply.Content</p>
        </div>
        </li>
        }
        </ul>
        </li>
        <hr />
        }

        </ul>

        @if (User.Identity.IsAuthenticated)
        {
        <div>
        <form asp-controller="Blog" asp-action="Comment">
        <input asp-for="Blog.Id" readonly hidden />
        <div class="form-group">
        <label for="comment">Comment</label>
        <textarea asp-for="Comment.Content" class="form-control" rows="3" required></textarea>
        <button type="submit" class="btn btn-outline-primary Blog-btn">Blog</button>
        </div>
        </form>
        </div>
        }
        else
        {
        <a class="reply-btn btn" asp-area="Identity" asp-page="/Account/Login" asp-route-ReturnUrl="~/Blog/@Model.Blog.Id">Login to Comment on this Blog</a>
        }

        </div>
        </div>
        *@
    </div>
</article>
@section Scripts{
    <script>
        $('[data-toggle="collapse"]').on('click', function() {
            var $this = $(this),
                $parent = typeof $this.data('parent') !== 'undefined' ? $($this.data('parent')) : undefined;
            if ($parent === undefined) { /* Just toggle my  */
                $this.find('.glyphicon').toggleClass('glyphicon-plus glyphicon-minus');
                return true;
            }

            /* Open element will be close if parent !== undefined */
            var currentIcon = $this.find('.glyphicon');
            currentIcon.toggleClass('glyphicon-plus glyphicon-minus');
            $parent.find('.glyphicon').not(currentIcon).removeClass('glyphicon-minus').addClass('glyphicon-plus');

        });
    </script>
}

QuickBlog/Views/Blog/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Clean Blog - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    @await Component.InvokeAsync("Navigation")

    <header class="masthead" style="background-image: url('@ViewData["HeaderImage"]')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="blog-heading">
                        <h1>@ViewData["HeaderTitle"]</h1>
                        <span class="meta">
                            Posted By
                            <a href="#">@ViewData["AthorName"]</a>
                            on @ViewData["BlogDate"]
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content-->
    <div class="content">
        @RenderBody()
    </div>
    <!-- Footer-->
    @await Component.InvokeAsync("Footer")
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

QuickBlog/Views/Blog/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - SB Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href="~/css/style.css" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        @await Component.InvokeAsync("AdminTopNav")
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                @await Component.InvokeAsync("AdminSideNav")
            </div>
            <div id="layoutSidenav_content">
                <main>
                    @RenderBody()
                </main>
                @await Component.InvokeAsync("AdminFooter")
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="~/js/script.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="~/assets/demo/chart-area-demo.js"></script>
        <script src="~/assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="~/js/datatables-simple-demo.js"></script>
         @RenderSection("Scripts", required: false)
    </body>
</html>